name = "cfnote"
compatibility_date = "2024-09-23"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "cfnote-db"
database_id = "3abd7367-e382-41d4-9539-a8db0b368208"

[[vectorize]]
binding = "VECTORIZE"
index_name = "cfnote-index"

[ai]
binding = "AI"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "cfnote_usage"
